# Generated by Django 3.1.3 on 2021-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='item_images/'),
        ),
    ]
