# Generated by Django 3.1.3 on 2021-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='type1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(default='default.jpg', upload_to='item_images/')),
            ],
        ),
    ]
