# Generated by Django 3.1.3 on 2021-02-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_type1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type1',
            new_name='typea',
        ),
    ]
