# Generated by Django 3.1.3 on 2021-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210219_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(default='default.jpg', upload_to='typeb_images/')),
            ],
        ),
        migrations.CreateModel(
            name='typec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(default='default.jpg', upload_to='typec_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='typea',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='typea_images/'),
        ),
    ]
