# Generated by Django 3.1.3 on 2021-03-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210220_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='typea',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
