# Generated by Django 3.1.3 on 2021-03-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_typea_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typea',
            name='category',
        ),
        migrations.AddField(
            model_name='typea',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
