# Generated by Django 3.1.3 on 2021-03-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210315_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typea',
            name='item_category',
        ),
        migrations.AddField(
            model_name='typea',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
