# Generated by Django 3.1.3 on 2021-03-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210315_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typea',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
