# Generated by Django 3.1.3 on 2021-04-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210415_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typea',
        ),
        migrations.DeleteModel(
            name='typeb',
        ),
        migrations.DeleteModel(
            name='typec',
        ),
    ]
